import os

import config

TFLITE_PATH = os.path.join(config.MODEL_OUT_DIR, "kws_model_int8.tflite")
HEADER_OUT_PATH = os.path.join(config.MODEL_OUT_DIR, "kws_model_data.h")

ARRAY_NAME = "g_kws_model_data"
LEN_NAME = "g_kws_model_data_len"


def export_to_c_header(tflite_path=TFLITE_PATH, out_path=HEADER_OUT_PATH):
    with open(tflite_path, "rb") as f:
        data = f.read()

    lines = []
    lines.append("// Auto-generated by export_esp32.py — do not edit by hand.")
    lines.append(f"// Source: {os.path.basename(tflite_path)} ({len(data)} bytes)")
    lines.append("#ifndef KWS_MODEL_DATA_H_")
    lines.append("#define KWS_MODEL_DATA_H_")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    # 16-byte alignment matters for TFLite Micro's FlatBuffer reader on some archs.
    lines.append(f"alignas(16) const unsigned char {ARRAY_NAME}[] = {{")

    hex_bytes = [f"0x{b:02x}" for b in data]
    for i in range(0, len(hex_bytes), 12):
        lines.append("  " + ", ".join(hex_bytes[i:i + 12]) + ",")

    lines.append("};")
    lines.append(f"const unsigned int {LEN_NAME} = {len(data)};")
    lines.append("")
    lines.append("#endif  // KWS_MODEL_DATA_H_")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {out_path}  ({len(data)} bytes -> {len(data)/1024:.1f} KB)")
    print(f"Array: {ARRAY_NAME}   Length symbol: {LEN_NAME}")
    print(
        "\nCopy this header into your ESP-IDF firmware project (e.g. "
        "firmware/main/kws_model_data.h) and reference it from your TFLM "
        "interpreter setup."
    )


if __name__ == "__main__":
    export_to_c_header()
